--Create a table and call it DEPT and insert it into the COMPANY1 Database.

mysql;
USE COMPANY1;

CREATE TABLE DEPT (
  DEPTNO INT,
  DNAME VARCHAR(255),
  LOC VARCHAR(255)
);

INSERT INTO DEPT VALUES(10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES(20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES(30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES(40, 'OPERATIONS', 'BOSTON');







